---
title: "Emory COVID-19 Response Collaborative"
subtitle: "EpiRHandbook Online Seminar"
date: "August 2021"
output: pdf_document
---

```{r setup, include=FALSE}

## define rmarkdown chunk options 
knitr::opts_chunk$set(echo = FALSE)

## load necessary packages 
pacman::p_load(
     dplyr,     ## pulling table together 
     stringr,   ## working character strings
     lubridate, ## work with times 
     flextable  ## formatting tables
)

```


```{r define_starts}

## define course start date and time (for first day)
st <- lubridate::ymd_hm("2021-08-13 10:00", tz = "CET")

## define course start date and time (for second day)
st2 <- lubridate::ymd_hm("2021-08-20 10:00", tz = "CET")

```



```{r contents_day1}


## define lectures, lengths and authors 
contents <- tribble(
      ~duration,         ~session,                                    ~author,           ~type, 
       5,                "Introduction to webinar series",            "ECRC Faculty",    "lecture", 
       5,                "Introduction to EpiRHandbook content",      "Neale",           "lecture",
       10,               "Why R?",                                    "Alex",            "lecture", 
       10,               "Case study layout & Rmarkdown & projects",  "Alex",            "lecture", 
       5,                "Parameterisation & Automation",             "Alex",            "lecture", 
       5,                "File paths & Importing data",               "Alex",            "lecture", 
       5,                "Case study: importing data",                "Alex",            "demo", 
       5,                "Data cleaning",                             "Henry",           "lecture", 
       5,                "Case study: data cleaning",                 "Henry",           "demo", 
       5,                "Merging data",                              "Henry",           "lecture", 
       5,                "Case study: merging data",                  "Henry",           "demo",
       5,                "Descriptive analysis",                      "Henry",           "lecture", 
       5,                "Case study: descriptive analysis",          "Alex",            "demo", 
       5,                "Statistical analysis",                      "Alex",            "lecture", 
       5,                "Case study: statistical analysis",          "Alex",            "demo", 
       5,                "Logistic regression",                       "Henry",           "lecture", 
       5,                "Case study: logistic regression",           "Henry",           "demo",
       15,               "Q&A session",                               "Team",            "demo"
      ) 

## add in the first start time (missing because of lag) 
contents$start <- st
contents$start[2:nrow(contents)] <- NA

for (i in 2:nrow(contents)) {
     contents$start[i] <- contents$start[i - 1] + lubridate::minutes(contents$duration[i - 1])
}

## format to be normal HH:MM 
contents <- contents %>% 
     mutate(start = stringr::str_c(
          lubridate::hour(start), 
          str_pad(
               lubridate::minute(start), 
               2, 
               pad = "0"
               ), 
          sep = ":"
     ))

## rearrange columns 
contents <- contents %>% 
     select(start, 
            session, 
            author)

```



```{r formatting_day1, warning = FALSE}

contents %>% 
     ## make in to a flextable 
     flextable() %>% 
     ## colour in the breaks grey 
     bg(., 
        i= ~ session == "BREAK", 
        part = "body", 
        bg = "grey90") %>% 
     ## colour in case study sessions light blue 
     bg(., 
        i = ~str_detect(session, "Case study"), 
        part = "body", 
        bg = "light blue") %>% 
     ## add in a title 
     add_header_row(
          top = TRUE,                # New header goes on top of existing header row
          values = c(
               str_glue("Day 1: Data management (", {format(st, format = "%d %B")}, ")"),     # Header values for each column below
                     "", 
                     "")) %>% 
     ## merge title across whole table 
     merge_at(i = 1, j = 1:3, part = "header") %>% 
     ## set widths
     width(j = 1, width = 1) %>% 
     width(j = 2, width = 3) %>% 
     width(j = 3, width = 1) %>% 
     ## fix titles 
      set_header_labels( 
           start   = "Time", 
           session = "Session content", 
           author  = "Facilitator" 
      )

```



\newpage

```{r contents_day2}




## define lectures, lengths and authors 
contents <- tribble(
      ~duration,       ~session,                                    ~author,           ~type, 
       5,              "Introduction to part two of series",        "Neale",           "lecture", 
       5,              "Introduction to visualisation (ggplot2)",   "Neale",           "lecture",
       5,              "{ggplot2} syntax & geometries",             "Neale",           "lecture", 
       5,              "{ggplot2} aesthetics",                      "Neale",           "lecture", 
       5,              "Faceting & highlighting",                   "Neale",           "lecture", 
       5,              "Scales & axis labels",                      "Neale",           "lecture",
       5,              "Themes",                                    "Neale",           "lecture",
       5,              "Barplots",                                  "Neale",           "lecture",
       5,              "Epicurves",                                 "Neale",           "lecture", 
       5,              "Demographic pyramids",                      "Neale",           "lecture", 
       5,              "Dynamic labels & captions",                 "Neale",           "lecture",   
       5,              "Combining plots",                           "Neale",           "lecture", 
       15,             "Basic GIS",                                 "Alex",            "lecture", 
       15,             "Q&A session",                               "Team",            "demo"
      ) 

## add in the first start time (missing because of lag) 
contents$start <- st
contents$start[2:nrow(contents)] <- NA

for (i in 2:nrow(contents)) {
     contents$start[i] <- contents$start[i - 1] + lubridate::minutes(contents$duration[i - 1])
}

## format to be normal HH:MM 
contents <- contents %>% 
     mutate(start = stringr::str_c(
          lubridate::hour(start), 
          str_pad(
               lubridate::minute(start), 
               2, 
               pad = "0"
               ), 
          sep = ":"
     ))

## rearrange columns 
contents <- contents %>% 
     select(start, 
            session, 
            author)

```



```{r formatting_day2, warning = FALSE}

contents %>% 
     ## make in to a flextable 
     flextable() %>% 
     ## colour in the breaks grey 
     bg(., 
        i = ~ session == "BREAK", 
        part = "body", 
        bg = "grey90") %>% 
     ## colour in case study sessions light blue 
     bg(., 
        i = ~str_detect(session, "Case study"), 
        part = "body", 
        bg = "light blue") %>% 
     ## add in a title 
     add_header_row(
          top = TRUE,                # New header goes on top of existing header row
          values = c(
               str_glue("Day 2: Data visualisation (", {format(st2, format = "%d %B")}, ")"),     # Header values for each column below
                     "", 
                     "")) %>% 
     ## merge title across whole table 
     merge_at(i = 1, j = 1:3, part = "header") %>% 
     ## set widths
     width(j = 1, width = 1) %>% 
     width(j = 2, width = 3) %>% 
     width(j = 3, width = 1) %>% 
     ## fix titles 
      set_header_labels( 
           start   = "Time", 
           session = "Session content", 
           author  = "Facilitator" 
      )

```


