---
title: "ECRC COVID-19 Training"
author: "EpiRHandbook Team"
date: "August 2021"
output: 
     powerpoint_presentation: 
          reference_doc: "template.pptx"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.width = 16, 
                      fig.height = 10)



## install and load necessary packages 
pacman::p_load(
  rio,        # importing data  
  here,       # relative file pathways  
  janitor,    # data cleaning and tables
  lubridate,  # working with dates
  tidyverse   # data management and visualization
)

```


## Introduction 

- Hello our name is 
  + blabla
  + blabla
  

::: notes
This is a speaker note.

- Use basic Markdown
- like this list
- *and inline formatting*
:::
  
## Visualisation 

Note to selves: 
I think the way [this presentation](https://www.cedricscherer.com/slides/2019-08-28-intro-ggplot-statsizw#20) 
breaks down ggplots line by line is probably the way to go! 



## side by side code outputs 


:::::: {.columns}
::: {.column}

```{r basic_plot, echo = TRUE}
## this shows the code that we use to create plot (nb. echo = TRUE)
our_plot <- ggplot(mtcars, aes(x = cyl, y = mpg)) + 
  geom_point()

```


:::

::: {.column}

```{r basic_plot_view, echo = FALSE}

## this shos the plot we created (nb echo = FALSE)
our_plot

```


:::
::::::





## side by side text 


:::::: {.columns}
::: {.column}

- testing  
  + bla 
  + bla 
- testing 
- testing 

:::

::: {.column}

- testing 
- testing 
- testing 

:::
::::::